#! /bin/sh

export TSLIB_ROOT=/usr/local/tslib
export TSLIB_TSDEVICE=/dev/input/event0
export TSLIB_CALIBFILE=/etc/pointercal
export TSLIB_CONFFILE=$TSLIB_ROOT/etc/ts.conf
export TSLIB_PLUGINDIR=$TSLIB_ROOT/lib/ts
export TSLIB_FBDEVICE=/dev/fb0
export TSLIB_CALIBFILE=/etc/pointercal
export POINTERCAL_FILE=/etc/pointercal
export TSLIB_CONSOLEDEVICE=none


export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/tslib/lib
export PATH=$TSLIB_ROOT/bin:$PATH


export QTDIR=/usr/local/qt5
export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/qt5/plugins
export QT_QPA_PLATFORM=linuxfb:fb=/dev/fb0

export QT_QPA_FONTDIR=/usr/local/qt5/lib/fonts
export QT_QPA_GENERIC_PLUGINS=tslib:$TSLIB_TSDEVICE
export LD_LIBRARY_PATH=/usr/local/qt5/lib:$LD_LIBRARY_PATH
export QT_DEBUG_PLUGINS=1

export QWS_KEYBOARD=USB:/dev/input/event0
export QWS_MOUSE_PROTO=Tslib:/dev/input/event0
export QWS_DISPLAY=LinuxFb:mmWidth91:mmHeight53:0
export QWS_SIZE=800x480
if [-e /etc/pointercal ]
then 
	rm  /etc/pointercal
	 /usr/local/tslib/bin/ts_calibrate &
else
	/usr/local/tslib/bin/ts_calibrate &
fi 
#	/test/qt_tools &

